name: Build and Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # or another OS if needed

    steps:
    - uses: actions/checkout@v2
    - name: Execute build script
      run: |
        chmod +x build.sh
        ./build.sh
